// Generates public/assets/css/icons-generated.css — a CSS-mask replacement
// for the Bootstrap Icons webfont/CDN CSS this site used to load in full
// (2000+ glyphs) for the ~90 it actually uses. Scans views/**/*.bxm,
// public/assets/js/*.js, and models/**/*.bx for literal "bi-*" class names
// (including ones picked dynamically at runtime, e.g. a ternary between two
// class strings, or interpolated from a data file like ProjectRegistry.bx's
// icon field — every case is still literal text somewhere in the source, so
// a plain grep-style scan finds them same as a static one) and emits one
// mask rule per icon actually referenced, so a future icon added to
// markup/JS/models is picked up automatically on the next build with no
// separate step to remember.
//
// Markup keeps using <i class="bi bi-star-fill">, same as before — only the
// CSS backing those classes changes, from @font-face + ::before{content:"\fNNN"}
// to background-color:currentColor masked by the icon's own SVG shape. This
// keeps every existing view/JS untouched (including JS that toggles icon
// classes directly, e.g. the post star-toggle button).
import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function walk(dir, exts, out = []) {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) walk(full, exts, out);
		else if (exts.some((ext) => entry.name.endsWith(ext))) out.push(full);
	}
	return out;
}

const sourceFiles = [
	...walk(join(root, "views"), [".bxm"]),
	...walk(join(root, "public/assets/js"), [".js"]),
	...walk(join(root, "models"), [".bx"]),
];

const iconNames = new Set();
const iconPattern = /\bbi-[a-z0-9-]+\b/g;
for (const file of sourceFiles) {
	const text = readFileSync(file, "utf8");
	for (const match of text.matchAll(iconPattern)) iconNames.add(match[0]);
}

const sorted = [...iconNames].sort();
const iconsDir = join(root, "node_modules/bootstrap-icons/icons");

const rules = [];
for (const className of sorted) {
	const svgName = className.slice("bi-".length) + ".svg";
	let svg;
	try {
		svg = readFileSync(join(iconsDir, svgName), "utf8");
	} catch {
		console.warn(`[build-icons] no bootstrap-icons source for .${className} (${svgName}) — skipping`);
		continue;
	}
	// Extract just the inner shape (path/g elements) and re-wrap with a fixed
	// 16x16 viewBox — this drops the original width/height/class/fill
	// attributes on the outer <svg> (irrelevant once embedded as a mask
	// source, since only the alpha/shape matters, not the original fill).
	const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
	const dataUri = "data:image/svg+xml," + encodeURIComponent(
		`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">${inner}</svg>`
	);
	// --bi-icon (referenced once, from the shared ::before rule below) rather
	// than repeating the data URI in both a -webkit-mask-image and a
	// mask-image declaration per icon — halves this file's size.
	rules.push(`.${className}::before { --bi-icon: url("${dataUri}"); }`);
}

const header = `/* Generated by scripts/build-icons.mjs — do not edit by hand.
   Regenerated on every build (see esbuild.config.mjs) from the bi-* class
   names actually referenced under views/ and public/assets/js/.
   Replaces the Bootstrap Icons webfont with per-icon CSS masks so only the
   ${sorted.length} glyphs in use ship, instead of the full ~2000-icon font. */

.bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
	content: "";
	display: inline-block;
	width: 1em;
	height: 1em;
	vertical-align: -.125em;
	background-color: currentColor;
	-webkit-mask-repeat: no-repeat;
	mask-repeat: no-repeat;
	-webkit-mask-position: center;
	mask-position: center;
	-webkit-mask-size: contain;
	mask-size: contain;
	-webkit-mask-image: var(--bi-icon);
	mask-image: var(--bi-icon);
}

`;

const outPath = join(root, "public/assets/css/icons-generated.css");
writeFileSync(outPath, header + rules.join("\n") + "\n");
console.log(`[build-icons] wrote ${sorted.length} icon(s) to public/assets/css/icons-generated.css`);
